spring:
  datasource:
    url: jdbc:mysql://localhost:33061/test_db
    username: root
    password: Abc@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
