server:
  port: 8762
spring:
  application:
    name: gateway
  cloud:
    discovery:
      client:
        simple:
          instances:
            catalog-service:
              - uri: lb://catalog-core-service
    gateway:
      routes:
        - id: catalog-service
          uri: lb://catalog-core-service
          predicates:
            - Path=/gateway/catalog-service/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'